define([
    './User',
    './Text',
    './Ticket',
    './EzTicket',
    './TextMessages',
    './Interceptor',
    './DashboardInterceptor',
    './EventManager',
    './TicketSearchLog',
    './AbstractTicket',
    './AbstractModel',
    './YouTube'
]);