define([
     './RegistrationCtrl',
     './LoginCtrl',
     './DashboardHeaderCtrl',
     './SearchCtrl',
     './SearchResultCtrl',
     './WorkonTextCtrl',
     './WorkonVideoCtrl',
     './LeftMenuCtrl',
     './AddTextCtrl',
     './PanelCtrl'
]);